name: JDCloud-ImmortalWrt

on:
  workflow_dispatch:
  workflow_call:
  # schedule:
  #   - cron: "0 18 * * *"

permissions:
  contents: write
  actions: write

jobs:
  Build:
    uses: ./.github/workflows/Build-OpenWrt.yml
    permissions:
      contents: write
      actions: write
    with:
      repo_url: https://github.com/laipeng668/immortalwrt.git
      repo_branch: master
      config_file: configs/JDCloud.config
      firmware_tag: JDCloud
      kernel_file: kernel-6.12
      artifact_prefix: Arthur.Athena
      manifest_file: immortalwrt-qualcommax-ipq60xx.manifest
      delete_old_workflows: true
      release_summary: >-
        深度定制开启全功能NSS的6.12内核隐私网关固件，默认地址 192.168.199.1。精简了无用组件，集成了 OpenClash、OAF、banIP、SQM 等高防组件，搭载 Argon 纯净主题，并支持满血 USB 存储自动挂载与 Wireguard 快速组网。具体详见JDCloud.config(NoWiFi.config)和General.config。
     